### ISSUE TITLE
Toggling contact-list

### ISSUE THREAD

**Issue by rykanohi1** [rykanohi1/Laptop-projects#10]
@joe-crick The onFocus event did the trick for toggling the contact-list, but I noticed that if the search bar component is clicked incorrectly(for instance, clicking on the search button instead of the input) then clicking outside of the component will toggle the contact-list on rather than toggling it off like it should be doing.

**Comment by joe-crick** [comment]
@rykanohi1 Check it in, and I'll look at it.

**Comment by rykanohi1** [comment]
@joe-crick  it's checked in

**Comment by joe-crick** [comment]
@rykanohi1 You have an `onBlur` event firing for a dom element--a `div` in this case--that wraps both your `input` and `ActionButton`. Move the `onBlur` from the `div` to the `input`, and this should be fixed. This is what created the weird display cycle, because the `onBlur` event was being fired somehow in relation to the `div` and all of its contents, not just the `input`.

```js
<div className="search-bar">  // <-- Removed here
        <input
          className="search-filter"
          type="search"
          placeholder="search contacts"
          value={this.state.searchTerm}
          onChange={this.updateSearch}
          onFocus={this.showContacts}
          onBlur={this.showContacts} // <-- Moved here
        />
        <ActionButton title="searchButton" 
                      label="search" 
                      imgSrc={this.props.imgSrc} 
                      action={this.search}/>           
        <ContactList className={this.state.isVisible ? 'show' : 'hide'} contacts={filteredContacts}/>
      </div>
```

**Comment by joe-crick** [comment]
Maybe renaming your method from `showContacts` to `toggleContacts` would be better, too. It more accurately describes what the method is doing.
