### ISSUE TITLE
changing structure of dropdown

### ISSUE THREAD

**Issue by rykanohi1** [rykanohi1/Laptop-projects#2]
how would I go about changing drop down to a stateless functional component and still have it perform the same functions? It seems as though using state in this component is making it more complicated then it needs to be.

**Comment by joe-crick** [comment]
Let's start with why you don't want dropdown to maintain its own state. What are the reasons? It could make sense for dropdown to maintain a small amount of state---specifically state that is less important to the application. How do you determine if the state for a component is less important to the overall application? You can ask yourself if the application needs to be able to recreate that state. For example, when you open the mail application is there anywhere you need to be able to set the state of a dropdown, say, to its expanded state? If the answer is no, then that suggests you might not need or want to manage the state of your dropdowns at the application level. It might make sense to keep this bit of state located in the dropdown itself---because this bit of state has very little impact.

This said, to answer the question about how to manage the state in a stateless functional component---you pass it in. It doesn't maintain its own state. It receives state from a parent component, or from a state container---such as a store or model.

One last thing---a note about writing GitHub issues: By default, if I create an issue on your board, you'll get an email. If you want me to receive an email when you create an issue on your board, you can @ mention me in the issue. To @ mention someone, you type an @ symbol, followed by their user name. For example, to @ mention you, I would type: @rykanohi1.

**Comment by joe-crick** [comment]
@rykanohi1 One more thing: You mention that the state is getting complicated. If you want, you can check your changes in, and I can review them in a PR, to see if I can give you some direction about how to simplify things.

Note: The above comment is a common way of @ mentioning someone in a comment.
