### ISSUE TITLE
test for search bar

### ISSUE THREAD

**Issue by rykanohi1** [rykanohi1/Laptop-projects#4]
@joe-crick can't figure out what's wrong with the test I have for my search bar component. "Comparing two different types of values. Expected boolean but received undefined."

**Comment by joe-crick** [comment]
There's a few things that happened.

1. Shallow rendering renders a component only one-level deep. That means it doesn't render out child components. The `imgSrc` property is being passed by `SearchBar` into `ActionButton`. When you `shallow` render this component, `ActionBar` isn't being rendered. 
2. The above means that you were using the `props` method incorrectly. There's a note on the `props` docs that says:

> When called on a shallow wrapper, `.props()` will return values for props on the **root node** that the component renders, not the component itself (meaning the whole, rendered component, children and all). _To return the props for the entire React component, use `wrapper.instance().props`_

So, there's two ways you can solve this. First:

```js
describe('SearchBar', () => {
  test('should display an icon if given one', () => {
    const expected = 'blank';
    const app = shallow(<SearchBar imgSrc="blank"/>);
    --> const actual = app.instance().props.imgSrc;
    expect(actual).toEqual(expected);
  })
});
```

Second:

```js
import React from 'react';
--> import {mount} from 'enzyme';
import SearchBar from './search-bar';

describe('SearchBar', () => {
  test('should display an icon if given one', () => {
    const expected = 'blank';
   --> const app = mount(<SearchBar imgSrc="blank"/>);
    const actual = app.props().imgSrc;
    expect(actual).toEqual(expected);
  })
});
```
Note that for the Second option to work, you'd have to adjust your `search-bar.js` component. `ActionButton` requires a function. If you don't pass it one, it raises an error. 

The main difference between the First option and the Second is that the Second is _not_ a unit test. It isn't a unit test, because it's also testing a child component. The Second is an integration test.
