### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by rykanohi1** [rykanohi1/Laptop-projects#9]
@joe-crick  I was able to get the contact-list to toggle in and out of visibility with an onclick event but I'm looking to use a different one. I've been looking for an event that fires when the inside of an input is being used, but I can't find any. I am also looking for a way to toggle the contact list when I click outside the element, and I keep coming across something called a wrapper ref. Is that something I should use? if so, could you explain how to use it?

**Comment by joe-crick** [comment]
@rykanohi1 

### Being Used
For events that work when you're inside an input and typing, try the `onKey` events. There are three of them: 

* `onKeyUp`: fired when a key is released.
* `onKeyDown`:  fired when a key is pressed down. Unlike the `keypress` event, the `keydown` event is fired for keys that produce a character value and for keys that do not produce a character value.
* `onKeyPress`:  fired when a key that produces a character value is pressed down.

Usually, `onKeyUp` is what you want, because it fires after a user is done with entering a value on the keyboard. 

The `event` object that is returned from a keyboard event has several properties. You can read more about keyboard events here: [Keyboard Events](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent). Keep a keen eye open while reading this documentation. In particular, pay attention to thumbs-down icons. They indicate that, while the functionality described exists, you shouldn't use it (i.e., it's deprecated).

### Click Outside the Element
For an even that fires when you click outside of the input, try `onBlur`.

I think you can probably accomplish the tasks you want, without having to use `ref`s. Most commonly, you'll need to use `ref`s if you have to `focus` (i.e., programmatically put the cursor in ) a field. 

If you want to read up on `ref`s, you can learn more here: [Refs](https://reactjs.org/docs/refs-and-the-dom.html).

**Comment by rykanohi1** [comment]
@joe-crick  When using the onKeyUp event, every time I type a character in the input the visibility of the contact list is toggled. Is there a way to only toggle it once one the first key I press?

**Comment by joe-crick** [comment]
@rykanohi1 It sounds like what you're trying to do is display data in the contact list--if there is data to be displayed. Is that correct? If so, then the best thing to do here would be for you to display the filtered contact list if there is data in it. That might look something like the code below.

_NOTE_: In the example, I did some refactoring. Rather than filtering the display items every time that the component renders, I moved contact list filtering to a function. Moving it to a function gives you more control. It makes the function testable, and doesn't require you to run the filter every time the render method might be called.

```js
import React, {Component} from 'react';
import ActionButton from '../action-button/action-button';
import ContactList from '../contact-list/contact-list';

export default class SearchBar extends Component {
  constructor(props) {
    super(props);
    this.updateSearch = this.updateSearch.bind(this);
    // --> Added this function <--
    this.filterContacts = this.filterContacts.bind(this);
    this.state = {
      searchTerm: '',
      contacts: props.contacts || [],
     // --> Added this state <--
      filteredContacts: [],
      isVisible: false
    };
  };

  search() {
    return true;
  };

   // --> Removed the showContacts function <--

   // --> Added the filterContacts function <--
  filterContacts(filter) {
    return filter
      ? this.state.contacts.filter(
        (contact) => contact.username.toLowerCase().startsWith(filter.toLowerCase()))
      : [];
  }

 // --> Updated the search function, so that it filters contacts when a search has been updated <--
  updateSearch({target: {value}}) {
    this.setState(() => ({
      searchTerm: value,
      filteredContacts: this.filterContacts(value)
    }));

  };

  render() {
   // --> Destructured these values from the state ( less typing :)  ) <--
    const {searchTerm, filteredContacts} = this.state;
    return (
      <!-- --> Removed the onKeyUp, and onBlur events <-- -->
      <div className="search-bar">
        <input
          className="search-filter"
          type="search"
          placeholder="search contacts"
          value={searchTerm}
          onChange={this.updateSearch}
        />
        <ActionButton title="searchButton"
                      label="search"
                      imgSrc={this.props.imgSrc}
                      action={this.search}/>
      <!-- --> Only render ContactsList if there are filtered contacts <--  -->
      {filteredContacts.length > 0 ? <ContactList contacts={filteredContacts}/> : null}
      </div>
    );
  };
}
```

**Comment by rykanohi1** [comment]
@joe-crick  though I do want the contact list to be displayed only if there is data, my main issue is with something else. I noticed that when clicking inside the contact search bar in hotmail, it brings up my list of contacts, but in order to get the contact list to go away, you need to click outside the search bar. Not only does the contact list appear when you click inside the search bar, it also only toggles the first time you click inside the search bar. So i'm not sure if there's one toggling method used for the contact list or two.

**Comment by joe-crick** [comment]
@rykanohi1 my guess is that this is happening on the `focus` event--`onFocus` in React. To toggle the contact suggestions on and off, you'd use a combination of `onFocus` (user has clicked on the input), and `onBlur` (user has left the input).
